/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    Canvas: typeof import('./src/views/Canvas.vue')['default']
    Header: typeof import('./src/views/Header/Header.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    MainView: typeof import('./src/views/MainView.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/views/Sidebar.vue')['default']
    SideBar: typeof import('./src/views/SideBar.vue')['default']
    UserInfo: typeof import('./src/views/Header/UserInfo.vue')['default']
  }
}
